# Generated by Django 3.0.2 on 2020-07-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200713_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='question_html',
        ),
    ]
