# Generated by Django 3.0.2 on 2020-07-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pic',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
